-- ==========================================================
-- AITDL AI AGENT BUILD SIGNATURE
-- ==========================================================
-- Architect    : Jawahar R Mallah
-- Designation  : AI Systems Architect & Author
-- Organization : AITDL Network | PrathamOne
-- Framework    : Autonomous AI Agent Development
-- Authored By  : Jawahar R Mallah
-- Version      : 1.1.0 (Supabase Core Migration)
-- Release Date : 29 March 2026
-- Environment  : Production
--
-- Signature    : Engineered by Jawahar R Mallah
-- Motto        : Crafted with Logic, Vision & AI
-- ==========================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "vector"; -- For AI Q&A similarity search (pgvector)

-- 2. INSTITUTES & ROLES
CREATE TABLE public.institutes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    logo_url TEXT,
    theme_config JSONB DEFAULT '{}'::jsonb,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. USER PROFILES & ROLES
-- Note: 'auth.users' is the Supabase internal table. This table links profiles to roles/institutes.
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
    institute_id UUID NOT NULL REFERENCES public.institutes(id),
    role TEXT NOT NULL DEFAULT 'student', -- student, lecturer, parent, admin, superadmin
    full_name TEXT NOT NULL,
    email TEXT,
    avatar_url TEXT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. STUDENT SPECIFIC DATA
CREATE TABLE public.students (
    id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    scholar_id TEXT, -- Institute's own ID for student
    parent_id UUID, -- References profiles(id) where role='parent'
    grade TEXT NOT NULL, -- e.g. "10", "11", "12"
    board TEXT DEFAULT 'MSBSHSE', 
    coins INTEGER DEFAULT 0,
    current_streak INTEGER DEFAULT 0,
    total_minutes_learning INTEGER DEFAULT 0,
    last_login_at TIMESTAMP WITH TIME ZONE
);

-- 5. LECTURER SPECIFIC DATA
CREATE TABLE public.lecturers (
    id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    qualification TEXT,
    subjects TEXT[] -- Array of subjects (e.g. ['Math', 'Physics'])
);

-- 6. CURRICULUM (Shared Content)
CREATE TABLE public.chapters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    board TEXT NOT NULL DEFAULT 'MSBSHSE',
    grade TEXT NOT NULL,
    subject TEXT NOT NULL,
    chapter_number INTEGER,
    title TEXT NOT NULL,
    summary TEXT,
    is_premium BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. LECTURES (Generated by AI for Lecturers)
CREATE TABLE public.lectures (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    institute_id UUID NOT NULL REFERENCES public.institutes(id),
    host_lecturer_id UUID REFERENCES public.lecturers(id),
    chapter_id UUID REFERENCES public.chapters(id),
    title TEXT NOT NULL,
    status TEXT DEFAULT 'draft', -- draft, published, completed
    script_json JSONB, -- Generated script + slides
    handout_url TEXT, -- Link to storage PDF
    is_live BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 8. STUDENT PROGRESS & ATTENDANCE
CREATE TABLE public.student_progress (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID NOT NULL REFERENCES public.students(id),
    chapter_id UUID NOT NULL REFERENCES public.chapters(id),
    percentage_complete INTEGER DEFAULT 0,
    completed_at TIMESTAMP WITH TIME ZONE,
    last_accessed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.attendance (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    institute_id UUID NOT NULL REFERENCES public.institutes(id),
    lecture_id UUID NOT NULL REFERENCES public.lectures(id),
    student_id UUID NOT NULL REFERENCES public.students(id),
    status TEXT DEFAULT 'absent', -- present, absent, late
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 9. ASSIGNMENTS & SUBMISSIONS
CREATE TABLE public.assignments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    institute_id UUID NOT NULL REFERENCES public.institutes(id),
    lecture_id UUID REFERENCES public.lectures(id),
    title TEXT NOT NULL,
    instructions TEXT,
    deadline TIMESTAMP WITH TIME ZONE,
    max_marks INTEGER DEFAULT 100
);

CREATE TABLE public.submissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    assignment_id UUID NOT NULL REFERENCES public.assignments(id),
    student_id UUID NOT NULL REFERENCES public.students(id),
    file_url TEXT,
    content_text TEXT,
    score INTEGER,
    feedback TEXT,
    graded_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 10. FINANCIALS (Recharge/Wallet Management)
CREATE TABLE public.recharges (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    student_id UUID NOT NULL REFERENCES public.students(id),
    amount NUMERIC(10,2) NOT NULL,
    status TEXT DEFAULT 'pending', -- pending, successful, failed
    provider_transaction_id TEXT, -- Razorpay/UPI ID
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- ============================================================
-- ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================================
ALTER TABLE public.institutes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lecturers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chapters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lectures ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recharges ENABLE ROW LEVEL SECURITY;

-- EXAMPLE POLICIES (Multi-tenant)
-- (Simplified for initial draft — to be expanded in Phase 1)

CREATE POLICY "Users can only view data from their own institute"
ON public.profiles
FOR SELECT
USING (institute_id = (auth.jwt() ->> 'institute_id')::uuid);

CREATE POLICY "Students can only see their own progress"
ON public.student_progress
FOR ALL
USING (student_id = auth.uid());

CREATE POLICY "Parents can see their linked students' progress"
ON public.student_progress
FOR SELECT
USING (student_id IN (SELECT student_id FROM public.students WHERE parent_id = auth.uid()));

-- LECTURE ACCESS (Public to Institute students)
CREATE POLICY "Institute students can see lectures"
ON public.lectures
FOR SELECT
USING (institute_id = (auth.jwt() ->> 'institute_id')::uuid);
